sudo: required

language: java

branches:
  except:
    - gh-pages

matrix:
  include:
    - jdk: openjdk8
      env: COVERALLS=yes
    - jdk: oraclejdk12
      addons:
        apt:
          packages:
            - openjdk-8-jdk
  fast_finish: true

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
#    - $HOME/.gradle/caches

install:
  - git clone -b libpcap-1.7.4 git://github.com/the-tcpdump-group/libpcap.git libpcap
  - cd libpcap
  - ./configure
  - make && sudo make install
  - cd ..

script:
  # sudo is needed for some unit tests.
  - |
    if [ "${COVERALLS}" = "yes"  ]
    then
      sudo ./gradlew build jacocoTestReport --info --no-daemon -Dorg.pcap4j.core.pcapLibName=/usr/local/lib/libpcap.so -Dorg.pcap4j.core.test.enableTimestampPrecisionTests=true
    else
      sudo ./gradlew build jacocoTestReport --info --no-daemon -Dorg.pcap4j.core.pcapLibName=/usr/local/lib/libpcap.so -Dorg.pcap4j.core.test.enableTimestampPrecisionTests=true -Pjre8_bin_path=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    fi

after_success:
  - |
    if [ "${COVERALLS}" = "yes"  ]
    then
      bash <(curl -s https://codecov.io/bash)
    fi

notifications:
  email:
    recipients:
      - kaitoy@pcap4j.org
    on_success: change
    on_failure: always
