version: 2.1

executors:
  docker-jdk10:
    docker:
      - image: circleci/openjdk:10.0.2-13-jdk

jobs:
  test:
    executor: docker-jdk10
    steps:
      - checkout
      - run:
          name: Install libpcap
          command: |
            sudo apt-get update
            sudo apt-get install -y libpcap0.8
      - run:
          name: Download Maven
          command: ./mvnw --version
      - run:
          name: Run mvnw verify
          # Run mvn directly rather than mvnw to execute java with root privileges that's needed for some of tests.
          command: sudo /home/circleci/.m2/wrapper/dists/apache-maven-3.6.1-bin/18t1vjepdne9cv9t0hdcik0hp1/apache-maven-3.6.1/bin/mvn verify --global-toolchains mvn/toolchains_circleci_10.xml

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: v1
